GET http://localhost:3000/api/products
###

GET http://localhost:3000/api/products/1
###

POST http://localhost:3000/api/products
Content-Type: application/json

{
    "type": "Klänning",
    "size": "XL",
    "color": "Gul"
}
###

PUT http://localhost:3000/api/products/2
Content-Type: application/json

{
    "type": "kjol",
    "size": "SX",
    "color": "Lila"
}
###

DELETE http://localhost:3000/api/products/16
###




