GET http://localhost:3000/api/products
###

GET http://localhost:3000/api/products/1
###

POST http://localhost:3000/api/products
Content-Type: application/json

{
    "type": "Klänning"
}
###
PUT http://localhost:3000/api/products/1
Content-Type: application/json

{
    "type": "kjol"
}
###

DELETE http://localhost:3000/api/products/1
###




